/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ApiContentResponse, CreateContentJson, UpdateContentJson } from '../models/index';
import {
  ApiContentResponseFromJSON,
  ApiContentResponseToJSON,
  CreateContentJsonFromJSON,
  CreateContentJsonToJSON,
  UpdateContentJsonFromJSON,
  UpdateContentJsonToJSON,
} from '../models/index';

export interface CountContentsRequest {
  keyword?: string | null;
  categoryId?: string | null;
  tags?: string | null;
  relationSourceContentId?: string | null;
}

export interface CreateContentRequest {
  createContentJson: CreateContentJson;
}

export interface DeleteContentRequest {
  id: string;
}

export interface FindContentRequest {
  id: string;
  draftKey?: string | null;
}

export interface GetContentsRequest {
  offset: number;
  limit: number;
  keyword?: string | null;
  categoryId?: string | null;
  tags?: string | null;
  relationSourceContentId?: string | null;
  statusKeys?: string | null;
}

export interface UpdateContentRequest {
  id: string;
  updateContentJson: UpdateContentJson;
}

/**
 *
 */
export class ApiContentsApi extends runtime.BaseAPI {
  /**
   */
  async countContentsRaw(
    requestParameters: CountContentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<number>> {
    const queryParameters: any = {};

    if (requestParameters['keyword'] != null) {
      queryParameters['keyword'] = requestParameters['keyword'];
    }

    if (requestParameters['categoryId'] != null) {
      queryParameters['category_id'] = requestParameters['categoryId'];
    }

    if (requestParameters['tags'] != null) {
      queryParameters['tags'] = requestParameters['tags'];
    }

    if (requestParameters['relationSourceContentId'] != null) {
      queryParameters['relation_source_content_id'] = requestParameters['relationSourceContentId'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/contents/count`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<number>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async countContents(
    requestParameters: CountContentsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<number> {
    const response = await this.countContentsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async createContentRaw(
    requestParameters: CreateContentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ApiContentResponse>> {
    if (requestParameters['createContentJson'] == null) {
      throw new runtime.RequiredError(
        'createContentJson',
        'Required parameter "createContentJson" was null or undefined when calling createContent().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/api/contents`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateContentJsonToJSON(requestParameters['createContentJson']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ApiContentResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async createContent(
    requestParameters: CreateContentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ApiContentResponse> {
    const response = await this.createContentRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async deleteContentRaw(
    requestParameters: DeleteContentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteContent().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/contents/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async deleteContent(
    requestParameters: DeleteContentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteContentRaw(requestParameters, initOverrides);
  }

  /**
   */
  async findContentRaw(
    requestParameters: FindContentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ApiContentResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling findContent().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['draftKey'] != null) {
      queryParameters['draft_key'] = requestParameters['draftKey'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/contents/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ApiContentResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async findContent(
    requestParameters: FindContentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ApiContentResponse> {
    const response = await this.findContentRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async getContentsRaw(
    requestParameters: GetContentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ApiContentResponse>>> {
    if (requestParameters['offset'] == null) {
      throw new runtime.RequiredError(
        'offset',
        'Required parameter "offset" was null or undefined when calling getContents().',
      );
    }

    if (requestParameters['limit'] == null) {
      throw new runtime.RequiredError(
        'limit',
        'Required parameter "limit" was null or undefined when calling getContents().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['offset'] != null) {
      queryParameters['offset'] = requestParameters['offset'];
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['keyword'] != null) {
      queryParameters['keyword'] = requestParameters['keyword'];
    }

    if (requestParameters['categoryId'] != null) {
      queryParameters['category_id'] = requestParameters['categoryId'];
    }

    if (requestParameters['tags'] != null) {
      queryParameters['tags'] = requestParameters['tags'];
    }

    if (requestParameters['relationSourceContentId'] != null) {
      queryParameters['relation_source_content_id'] = requestParameters['relationSourceContentId'];
    }

    if (requestParameters['statusKeys'] != null) {
      queryParameters['status_keys'] = requestParameters['statusKeys'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/contents`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ApiContentResponseFromJSON),
    );
  }

  /**
   */
  async getContents(
    requestParameters: GetContentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ApiContentResponse>> {
    const response = await this.getContentsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async updateContentRaw(
    requestParameters: UpdateContentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ApiContentResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling updateContent().',
      );
    }

    if (requestParameters['updateContentJson'] == null) {
      throw new runtime.RequiredError(
        'updateContentJson',
        'Required parameter "updateContentJson" was null or undefined when calling updateContent().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/api/contents/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateContentJsonToJSON(requestParameters['updateContentJson']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ApiContentResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async updateContent(
    requestParameters: UpdateContentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ApiContentResponse> {
    const response = await this.updateContentRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
