/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Category, CreateCategoryJson, UpdateCategoryJson } from '../models/index';
import {
  CategoryFromJSON,
  CategoryToJSON,
  CreateCategoryJsonFromJSON,
  CreateCategoryJsonToJSON,
  UpdateCategoryJsonFromJSON,
  UpdateCategoryJsonToJSON,
} from '../models/index';

export interface CreateCategoryRequest {
  createCategoryJson: CreateCategoryJson;
}

export interface DeleteCategoryRequest {
  id: string;
}

export interface FindCategoryRequest {
  id: string;
}

export interface GetCategoriesRequest {
  offset: number;
  limit: number;
}

export interface UpdateCategoryRequest {
  id: string;
  updateCategoryJson: UpdateCategoryJson;
}

/**
 *
 */
export class ApiCategoriesApi extends runtime.BaseAPI {
  /**
   */
  async countCategoriesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<number>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/categories/count`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<number>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async countCategories(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<number> {
    const response = await this.countCategoriesRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async createCategoryRaw(
    requestParameters: CreateCategoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Category>> {
    if (requestParameters['createCategoryJson'] == null) {
      throw new runtime.RequiredError(
        'createCategoryJson',
        'Required parameter "createCategoryJson" was null or undefined when calling createCategory().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/api/categories`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateCategoryJsonToJSON(requestParameters['createCategoryJson']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => CategoryFromJSON(jsonValue));
  }

  /**
   */
  async createCategory(
    requestParameters: CreateCategoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Category> {
    const response = await this.createCategoryRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async deleteCategoryRaw(
    requestParameters: DeleteCategoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteCategory().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/categories/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async deleteCategory(
    requestParameters: DeleteCategoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteCategoryRaw(requestParameters, initOverrides);
  }

  /**
   */
  async findCategoryRaw(
    requestParameters: FindCategoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Category>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling findCategory().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/categories/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => CategoryFromJSON(jsonValue));
  }

  /**
   */
  async findCategory(
    requestParameters: FindCategoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Category> {
    const response = await this.findCategoryRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async getCategoriesRaw(
    requestParameters: GetCategoriesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Category>>> {
    if (requestParameters['offset'] == null) {
      throw new runtime.RequiredError(
        'offset',
        'Required parameter "offset" was null or undefined when calling getCategories().',
      );
    }

    if (requestParameters['limit'] == null) {
      throw new runtime.RequiredError(
        'limit',
        'Required parameter "limit" was null or undefined when calling getCategories().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['offset'] != null) {
      queryParameters['offset'] = requestParameters['offset'];
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/categories`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryFromJSON));
  }

  /**
   */
  async getCategories(
    requestParameters: GetCategoriesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Category>> {
    const response = await this.getCategoriesRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async updateCategoryRaw(
    requestParameters: UpdateCategoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Category>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling updateCategory().',
      );
    }

    if (requestParameters['updateCategoryJson'] == null) {
      throw new runtime.RequiredError(
        'updateCategoryJson',
        'Required parameter "updateCategoryJson" was null or undefined when calling updateCategory().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/api/categories/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateCategoryJsonToJSON(requestParameters['updateCategoryJson']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => CategoryFromJSON(jsonValue));
  }

  /**
   */
  async updateCategory(
    requestParameters: UpdateCategoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Category> {
    const response = await this.updateCategoryRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
