/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CreateTagJson, Tag, UpdateTagJson } from '../models/index';
import {
  CreateTagJsonFromJSON,
  CreateTagJsonToJSON,
  TagFromJSON,
  TagToJSON,
  UpdateTagJsonFromJSON,
  UpdateTagJsonToJSON,
} from '../models/index';

export interface CountTagsRequest {
  keyword?: string | null;
}

export interface CreateTagRequest {
  createTagJson: CreateTagJson;
}

export interface DeleteTagRequest {
  id: string;
}

export interface FindTagRequest {
  id: string;
}

export interface GetTagsRequest {
  offset: number;
  limit: number;
  keyword?: string | null;
}

export interface UpdateTagRequest {
  id: string;
  updateTagJson: UpdateTagJson;
}

/**
 *
 */
export class ApiTagsApi extends runtime.BaseAPI {
  /**
   */
  async countTagsRaw(
    requestParameters: CountTagsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<number>> {
    const queryParameters: any = {};

    if (requestParameters['keyword'] != null) {
      queryParameters['keyword'] = requestParameters['keyword'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/tags/count`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<number>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async countTags(
    requestParameters: CountTagsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<number> {
    const response = await this.countTagsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async createTagRaw(
    requestParameters: CreateTagRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Tag>> {
    if (requestParameters['createTagJson'] == null) {
      throw new runtime.RequiredError(
        'createTagJson',
        'Required parameter "createTagJson" was null or undefined when calling createTag().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/api/tags`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateTagJsonToJSON(requestParameters['createTagJson']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TagFromJSON(jsonValue));
  }

  /**
   */
  async createTag(
    requestParameters: CreateTagRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Tag> {
    const response = await this.createTagRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async deleteTagRaw(
    requestParameters: DeleteTagRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteTag().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/tags/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async deleteTag(
    requestParameters: DeleteTagRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteTagRaw(requestParameters, initOverrides);
  }

  /**
   */
  async findTagRaw(
    requestParameters: FindTagRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Tag>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling findTag().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/tags/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TagFromJSON(jsonValue));
  }

  /**
   */
  async findTag(
    requestParameters: FindTagRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Tag> {
    const response = await this.findTagRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async getTagsRaw(
    requestParameters: GetTagsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Tag>>> {
    if (requestParameters['offset'] == null) {
      throw new runtime.RequiredError(
        'offset',
        'Required parameter "offset" was null or undefined when calling getTags().',
      );
    }

    if (requestParameters['limit'] == null) {
      throw new runtime.RequiredError(
        'limit',
        'Required parameter "limit" was null or undefined when calling getTags().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['offset'] != null) {
      queryParameters['offset'] = requestParameters['offset'];
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['keyword'] != null) {
      queryParameters['keyword'] = requestParameters['keyword'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/tags`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TagFromJSON));
  }

  /**
   */
  async getTags(
    requestParameters: GetTagsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Tag>> {
    const response = await this.getTagsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async updateTagRaw(
    requestParameters: UpdateTagRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Tag>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling updateTag().',
      );
    }

    if (requestParameters['updateTagJson'] == null) {
      throw new runtime.RequiredError(
        'updateTagJson',
        'Required parameter "updateTagJson" was null or undefined when calling updateTag().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/api/tags/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateTagJsonToJSON(requestParameters['updateTagJson']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TagFromJSON(jsonValue));
  }

  /**
   */
  async updateTag(
    requestParameters: UpdateTagRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Tag> {
    const response = await this.updateTagRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
