/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdatedBy } from './UpdatedBy';
import {
  UpdatedByFromJSON,
  UpdatedByFromJSONTyped,
  UpdatedByToJSON,
  UpdatedByToJSONTyped,
} from './UpdatedBy';
import type { CreatedBy } from './CreatedBy';
import {
  CreatedByFromJSON,
  CreatedByFromJSONTyped,
  CreatedByToJSON,
  CreatedByToJSONTyped,
} from './CreatedBy';
import type { Tag } from './Tag';
import { TagFromJSON, TagFromJSONTyped, TagToJSON, TagToJSONTyped } from './Tag';
import type { ContentCategory } from './ContentCategory';
import {
  ContentCategoryFromJSON,
  ContentCategoryFromJSONTyped,
  ContentCategoryToJSON,
  ContentCategoryToJSONTyped,
} from './ContentCategory';

/**
 * API レスポンス用の Content 構造体
 * fields を html 文字列に変換して返却する
 * @export
 * @interface ApiContentResponse
 */
export interface ApiContentResponse {
  /**
   *
   * @type {Array<ContentCategory>}
   * @memberof ApiContentResponse
   */
  categories: Array<ContentCategory>;
  /**
   *
   * @type {string}
   * @memberof ApiContentResponse
   */
  createdAt: string;
  /**
   *
   * @type {CreatedBy}
   * @memberof ApiContentResponse
   */
  createdBy: CreatedBy;
  /**
   *
   * @type {string}
   * @memberof ApiContentResponse
   */
  customUrl?: string | null;
  /**
   *
   * @type {string}
   * @memberof ApiContentResponse
   */
  draftKey: string;
  /**
   * fields を HTML に変換した文字列
   * @type {string}
   * @memberof ApiContentResponse
   */
  html: string;
  /**
   *
   * @type {string}
   * @memberof ApiContentResponse
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof ApiContentResponse
   */
  isPublic: boolean;
  /**
   *
   * @type {string}
   * @memberof ApiContentResponse
   */
  publishedAt?: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof ApiContentResponse
   */
  relatedContentIds: Array<string>;
  /**
   *
   * @type {any}
   * @memberof ApiContentResponse
   */
  seo?: any | null;
  /**
   *
   * @type {string}
   * @memberof ApiContentResponse
   */
  statusKey: string;
  /**
   *
   * @type {string}
   * @memberof ApiContentResponse
   */
  statusName: string;
  /**
   *
   * @type {Array<Tag>}
   * @memberof ApiContentResponse
   */
  tags: Array<Tag>;
  /**
   *
   * @type {any}
   * @memberof ApiContentResponse
   */
  thumbnail?: any | null;
  /**
   *
   * @type {string}
   * @memberof ApiContentResponse
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ApiContentResponse
   */
  updatedAt: string;
  /**
   *
   * @type {UpdatedBy}
   * @memberof ApiContentResponse
   */
  updatedBy: UpdatedBy;
}

/**
 * Check if a given object implements the ApiContentResponse interface.
 */
export function instanceOfApiContentResponse(value: object): value is ApiContentResponse {
  if (!('categories' in value) || value['categories'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
  if (!('draftKey' in value) || value['draftKey'] === undefined) return false;
  if (!('html' in value) || value['html'] === undefined) return false;
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
  if (!('relatedContentIds' in value) || value['relatedContentIds'] === undefined) return false;
  if (!('statusKey' in value) || value['statusKey'] === undefined) return false;
  if (!('statusName' in value) || value['statusName'] === undefined) return false;
  if (!('tags' in value) || value['tags'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
  return true;
}

export function ApiContentResponseFromJSON(json: any): ApiContentResponse {
  return ApiContentResponseFromJSONTyped(json, false);
}

export function ApiContentResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApiContentResponse {
  if (json == null) {
    return json;
  }
  return {
    categories: (json['categories'] as Array<any>).map(ContentCategoryFromJSON),
    createdAt: json['created_at'],
    createdBy: CreatedByFromJSON(json['created_by']),
    customUrl: json['custom_url'] == null ? undefined : json['custom_url'],
    draftKey: json['draft_key'],
    html: json['html'],
    id: json['id'],
    isPublic: json['is_public'],
    publishedAt: json['published_at'] == null ? undefined : json['published_at'],
    relatedContentIds: json['related_content_ids'],
    seo: json['seo'] == null ? undefined : json['seo'],
    statusKey: json['status_key'],
    statusName: json['status_name'],
    tags: (json['tags'] as Array<any>).map(TagFromJSON),
    thumbnail: json['thumbnail'] == null ? undefined : json['thumbnail'],
    title: json['title'],
    updatedAt: json['updated_at'],
    updatedBy: UpdatedByFromJSON(json['updated_by']),
  };
}

export function ApiContentResponseToJSON(json: any): ApiContentResponse {
  return ApiContentResponseToJSONTyped(json, false);
}

export function ApiContentResponseToJSONTyped(
  value?: ApiContentResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    categories: (value['categories'] as Array<any>).map(ContentCategoryToJSON),
    created_at: value['createdAt'],
    created_by: CreatedByToJSON(value['createdBy']),
    custom_url: value['customUrl'],
    draft_key: value['draftKey'],
    html: value['html'],
    id: value['id'],
    is_public: value['isPublic'],
    published_at: value['publishedAt'],
    related_content_ids: value['relatedContentIds'],
    seo: value['seo'],
    status_key: value['statusKey'],
    status_name: value['statusName'],
    tags: (value['tags'] as Array<any>).map(TagToJSON),
    thumbnail: value['thumbnail'],
    title: value['title'],
    updated_at: value['updatedAt'],
    updated_by: UpdatedByToJSON(value['updatedBy']),
  };
}
