/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Category
 */
export interface Category {
  /**
   *
   * @type {string}
   * @memberof Category
   */
  apiIdentifier: string;
  /**
   *
   * @type {string}
   * @memberof Category
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof Category
   */
  isPublished: boolean;
  /**
   *
   * @type {string}
   * @memberof Category
   */
  name: string;
}

/**
 * Check if a given object implements the Category interface.
 */
export function instanceOfCategory(value: object): value is Category {
  if (!('apiIdentifier' in value) || value['apiIdentifier'] === undefined) return false;
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('isPublished' in value) || value['isPublished'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function CategoryFromJSON(json: any): Category {
  return CategoryFromJSONTyped(json, false);
}

export function CategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Category {
  if (json == null) {
    return json;
  }
  return {
    apiIdentifier: json['api_identifier'],
    id: json['id'],
    isPublished: json['is_published'],
    name: json['name'],
  };
}

export function CategoryToJSON(json: any): Category {
  return CategoryToJSONTyped(json, false);
}

export function CategoryToJSONTyped(
  value?: Category | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    api_identifier: value['apiIdentifier'],
    id: value['id'],
    is_published: value['isPublished'],
    name: value['name'],
  };
}
