/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Field } from './Field';
import { FieldFromJSON, FieldFromJSONTyped, FieldToJSON, FieldToJSONTyped } from './Field';
import type { UpdatedBy } from './UpdatedBy';
import {
  UpdatedByFromJSON,
  UpdatedByFromJSONTyped,
  UpdatedByToJSON,
  UpdatedByToJSONTyped,
} from './UpdatedBy';
import type { CreatedBy } from './CreatedBy';
import {
  CreatedByFromJSON,
  CreatedByFromJSONTyped,
  CreatedByToJSON,
  CreatedByToJSONTyped,
} from './CreatedBy';
import type { Tag } from './Tag';
import { TagFromJSON, TagFromJSONTyped, TagToJSON, TagToJSONTyped } from './Tag';
import type { ContentCategory } from './ContentCategory';
import {
  ContentCategoryFromJSON,
  ContentCategoryFromJSONTyped,
  ContentCategoryToJSON,
  ContentCategoryToJSONTyped,
} from './ContentCategory';

/**
 *
 * @export
 * @interface Content
 */
export interface Content {
  /**
   *
   * @type {Array<ContentCategory>}
   * @memberof Content
   */
  categories: Array<ContentCategory>;
  /**
   *
   * @type {string}
   * @memberof Content
   */
  createdAt: string;
  /**
   *
   * @type {CreatedBy}
   * @memberof Content
   */
  createdBy: CreatedBy;
  /**
   *
   * @type {string}
   * @memberof Content
   */
  customUrl?: string | null;
  /**
   *
   * @type {string}
   * @memberof Content
   */
  draftKey: string;
  /**
   *
   * @type {Array<Field>}
   * @memberof Content
   */
  fields: Array<Field>;
  /**
   *
   * @type {string}
   * @memberof Content
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof Content
   */
  isPublic: boolean;
  /**
   *
   * @type {string}
   * @memberof Content
   */
  publishedAt?: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof Content
   */
  relatedContentIds: Array<string>;
  /**
   *
   * @type {any}
   * @memberof Content
   */
  seo?: any | null;
  /**
   *
   * @type {string}
   * @memberof Content
   */
  statusKey: string;
  /**
   *
   * @type {string}
   * @memberof Content
   */
  statusName: string;
  /**
   *
   * @type {Array<Tag>}
   * @memberof Content
   */
  tags: Array<Tag>;
  /**
   *
   * @type {any}
   * @memberof Content
   */
  thumbnail?: any | null;
  /**
   *
   * @type {string}
   * @memberof Content
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof Content
   */
  updatedAt: string;
  /**
   *
   * @type {UpdatedBy}
   * @memberof Content
   */
  updatedBy: UpdatedBy;
}

/**
 * Check if a given object implements the Content interface.
 */
export function instanceOfContent(value: object): value is Content {
  if (!('categories' in value) || value['categories'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
  if (!('draftKey' in value) || value['draftKey'] === undefined) return false;
  if (!('fields' in value) || value['fields'] === undefined) return false;
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
  if (!('relatedContentIds' in value) || value['relatedContentIds'] === undefined) return false;
  if (!('statusKey' in value) || value['statusKey'] === undefined) return false;
  if (!('statusName' in value) || value['statusName'] === undefined) return false;
  if (!('tags' in value) || value['tags'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
  return true;
}

export function ContentFromJSON(json: any): Content {
  return ContentFromJSONTyped(json, false);
}

export function ContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Content {
  if (json == null) {
    return json;
  }
  return {
    categories: (json['categories'] as Array<any>).map(ContentCategoryFromJSON),
    createdAt: json['created_at'],
    createdBy: CreatedByFromJSON(json['created_by']),
    customUrl: json['custom_url'] == null ? undefined : json['custom_url'],
    draftKey: json['draft_key'],
    fields: (json['fields'] as Array<any>).map(FieldFromJSON),
    id: json['id'],
    isPublic: json['is_public'],
    publishedAt: json['published_at'] == null ? undefined : json['published_at'],
    relatedContentIds: json['related_content_ids'],
    seo: json['seo'] == null ? undefined : json['seo'],
    statusKey: json['status_key'],
    statusName: json['status_name'],
    tags: (json['tags'] as Array<any>).map(TagFromJSON),
    thumbnail: json['thumbnail'] == null ? undefined : json['thumbnail'],
    title: json['title'],
    updatedAt: json['updated_at'],
    updatedBy: UpdatedByFromJSON(json['updated_by']),
  };
}

export function ContentToJSON(json: any): Content {
  return ContentToJSONTyped(json, false);
}

export function ContentToJSONTyped(
  value?: Content | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    categories: (value['categories'] as Array<any>).map(ContentCategoryToJSON),
    created_at: value['createdAt'],
    created_by: CreatedByToJSON(value['createdBy']),
    custom_url: value['customUrl'],
    draft_key: value['draftKey'],
    fields: (value['fields'] as Array<any>).map(FieldToJSON),
    id: value['id'],
    is_public: value['isPublic'],
    published_at: value['publishedAt'],
    related_content_ids: value['relatedContentIds'],
    seo: value['seo'],
    status_key: value['statusKey'],
    status_name: value['statusName'],
    tags: (value['tags'] as Array<any>).map(TagToJSON),
    thumbnail: value['thumbnail'],
    title: value['title'],
    updated_at: value['updatedAt'],
    updated_by: UpdatedByToJSON(value['updatedBy']),
  };
}
