/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ContentCategory
 */
export interface ContentCategory {
  /**
   *
   * @type {string}
   * @memberof ContentCategory
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ContentCategory
   */
  name: string;
}

/**
 * Check if a given object implements the ContentCategory interface.
 */
export function instanceOfContentCategory(value: object): value is ContentCategory {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function ContentCategoryFromJSON(json: any): ContentCategory {
  return ContentCategoryFromJSONTyped(json, false);
}

export function ContentCategoryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ContentCategory {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
  };
}

export function ContentCategoryToJSON(json: any): ContentCategory {
  return ContentCategoryToJSONTyped(json, false);
}

export function ContentCategoryToJSONTyped(
  value?: ContentCategory | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
  };
}
