/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateTagJson
 */
export interface CreateTagJson {
  /**
   *
   * @type {string}
   * @memberof CreateTagJson
   */
  name: string;
}

/**
 * Check if a given object implements the CreateTagJson interface.
 */
export function instanceOfCreateTagJson(value: object): value is CreateTagJson {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function CreateTagJsonFromJSON(json: any): CreateTagJson {
  return CreateTagJsonFromJSONTyped(json, false);
}

export function CreateTagJsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTagJson {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
  };
}

export function CreateTagJsonToJSON(json: any): CreateTagJson {
  return CreateTagJsonToJSONTyped(json, false);
}

export function CreateTagJsonToJSONTyped(
  value?: CreateTagJson | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
  };
}
