/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateCategoryJson
 */
export interface CreateCategoryJson {
  /**
   *
   * @type {string}
   * @memberof CreateCategoryJson
   */
  apiIdentifier: string;
  /**
   *
   * @type {boolean}
   * @memberof CreateCategoryJson
   */
  isPublished: boolean;
  /**
   *
   * @type {string}
   * @memberof CreateCategoryJson
   */
  name: string;
}

/**
 * Check if a given object implements the CreateCategoryJson interface.
 */
export function instanceOfCreateCategoryJson(value: object): value is CreateCategoryJson {
  if (!('apiIdentifier' in value) || value['apiIdentifier'] === undefined) return false;
  if (!('isPublished' in value) || value['isPublished'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function CreateCategoryJsonFromJSON(json: any): CreateCategoryJson {
  return CreateCategoryJsonFromJSONTyped(json, false);
}

export function CreateCategoryJsonFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateCategoryJson {
  if (json == null) {
    return json;
  }
  return {
    apiIdentifier: json['api_identifier'],
    isPublished: json['is_published'],
    name: json['name'],
  };
}

export function CreateCategoryJsonToJSON(json: any): CreateCategoryJson {
  return CreateCategoryJsonToJSONTyped(json, false);
}

export function CreateCategoryJsonToJSONTyped(
  value?: CreateCategoryJson | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    api_identifier: value['apiIdentifier'],
    is_published: value['isPublished'],
    name: value['name'],
  };
}
