/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateContentJson
 */
export interface CreateContentJson {
  /**
   *
   * @type {Array<string>}
   * @memberof CreateContentJson
   */
  categoryIds: Array<string>;
  /**
   *
   * @type {string}
   * @memberof CreateContentJson
   */
  customUrl?: string | null;
  /**
   *
   * @type {any}
   * @memberof CreateContentJson
   */
  fields: any | null;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateContentJson
   */
  relatedContentIds: Array<string>;
  /**
   *
   * @type {any}
   * @memberof CreateContentJson
   */
  seo?: any | null;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateContentJson
   */
  tagIds: Array<string>;
  /**
   *
   * @type {any}
   * @memberof CreateContentJson
   */
  thumbnail?: any | null;
  /**
   *
   * @type {string}
   * @memberof CreateContentJson
   */
  title: string;
}

/**
 * Check if a given object implements the CreateContentJson interface.
 */
export function instanceOfCreateContentJson(value: object): value is CreateContentJson {
  if (!('categoryIds' in value) || value['categoryIds'] === undefined) return false;
  if (!('fields' in value) || value['fields'] === undefined) return false;
  if (!('relatedContentIds' in value) || value['relatedContentIds'] === undefined) return false;
  if (!('tagIds' in value) || value['tagIds'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  return true;
}

export function CreateContentJsonFromJSON(json: any): CreateContentJson {
  return CreateContentJsonFromJSONTyped(json, false);
}

export function CreateContentJsonFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateContentJson {
  if (json == null) {
    return json;
  }
  return {
    categoryIds: json['category_ids'],
    customUrl: json['custom_url'] == null ? undefined : json['custom_url'],
    fields: json['fields'],
    relatedContentIds: json['related_content_ids'],
    seo: json['seo'] == null ? undefined : json['seo'],
    tagIds: json['tag_ids'],
    thumbnail: json['thumbnail'] == null ? undefined : json['thumbnail'],
    title: json['title'],
  };
}

export function CreateContentJsonToJSON(json: any): CreateContentJson {
  return CreateContentJsonToJSONTyped(json, false);
}

export function CreateContentJsonToJSONTyped(
  value?: CreateContentJson | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    category_ids: value['categoryIds'],
    custom_url: value['customUrl'],
    fields: value['fields'],
    related_content_ids: value['relatedContentIds'],
    seo: value['seo'],
    tag_ids: value['tagIds'],
    thumbnail: value['thumbnail'],
    title: value['title'],
  };
}
