/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreatedBy
 */
export interface CreatedBy {
  /**
   *
   * @type {string}
   * @memberof CreatedBy
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof CreatedBy
   */
  name: string;
}

/**
 * Check if a given object implements the CreatedBy interface.
 */
export function instanceOfCreatedBy(value: object): value is CreatedBy {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function CreatedByFromJSON(json: any): CreatedBy {
  return CreatedByFromJSONTyped(json, false);
}

export function CreatedByFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedBy {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
  };
}

export function CreatedByToJSON(json: any): CreatedBy {
  return CreatedByToJSONTyped(json, false);
}

export function CreatedByToJSONTyped(
  value?: CreatedBy | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
  };
}
