/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CustomSectionStatus = {
  Enable: 'Enable',
  Disable: 'Disable',
} as const;
export type CustomSectionStatus = (typeof CustomSectionStatus)[keyof typeof CustomSectionStatus];

export function instanceOfCustomSectionStatus(value: any): boolean {
  for (const key in CustomSectionStatus) {
    if (Object.prototype.hasOwnProperty.call(CustomSectionStatus, key)) {
      if (CustomSectionStatus[key as keyof typeof CustomSectionStatus] === value) {
        return true;
      }
    }
  }
  return false;
}

export function CustomSectionStatusFromJSON(json: any): CustomSectionStatus {
  return CustomSectionStatusFromJSONTyped(json, false);
}

export function CustomSectionStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CustomSectionStatus {
  return json as CustomSectionStatus;
}

export function CustomSectionStatusToJSON(value?: CustomSectionStatus | null): any {
  return value as any;
}

export function CustomSectionStatusToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): CustomSectionStatus {
  return value as CustomSectionStatus;
}
