/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdatedBy } from './UpdatedBy';
import {
  UpdatedByFromJSON,
  UpdatedByFromJSONTyped,
  UpdatedByToJSON,
  UpdatedByToJSONTyped,
} from './UpdatedBy';
import type { CreatedBy } from './CreatedBy';
import {
  CreatedByFromJSON,
  CreatedByFromJSONTyped,
  CreatedByToJSON,
  CreatedByToJSONTyped,
} from './CreatedBy';
import type { CustomSectionField } from './CustomSectionField';
import {
  CustomSectionFieldFromJSON,
  CustomSectionFieldFromJSONTyped,
  CustomSectionFieldToJSON,
  CustomSectionFieldToJSONTyped,
} from './CustomSectionField';
import type { CustomSectionStatus } from './CustomSectionStatus';
import {
  CustomSectionStatusFromJSON,
  CustomSectionStatusFromJSONTyped,
  CustomSectionStatusToJSON,
  CustomSectionStatusToJSONTyped,
} from './CustomSectionStatus';

/**
 *
 * @export
 * @interface CustomSection
 */
export interface CustomSection {
  /**
   *
   * @type {string}
   * @memberof CustomSection
   */
  createdAt: string;
  /**
   *
   * @type {CreatedBy}
   * @memberof CustomSection
   */
  createdBy: CreatedBy;
  /**
   *
   * @type {string}
   * @memberof CustomSection
   */
  description: string;
  /**
   *
   * @type {Array<CustomSectionField>}
   * @memberof CustomSection
   */
  fields: Array<CustomSectionField>;
  /**
   *
   * @type {string}
   * @memberof CustomSection
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof CustomSection
   */
  name: string;
  /**
   *
   * @type {CustomSectionStatus}
   * @memberof CustomSection
   */
  status: CustomSectionStatus;
  /**
   *
   * @type {string}
   * @memberof CustomSection
   */
  updatedAt: string;
  /**
   *
   * @type {UpdatedBy}
   * @memberof CustomSection
   */
  updatedBy: UpdatedBy;
}

/**
 * Check if a given object implements the CustomSection interface.
 */
export function instanceOfCustomSection(value: object): value is CustomSection {
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('fields' in value) || value['fields'] === undefined) return false;
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('status' in value) || value['status'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
  return true;
}

export function CustomSectionFromJSON(json: any): CustomSection {
  return CustomSectionFromJSONTyped(json, false);
}

export function CustomSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomSection {
  if (json == null) {
    return json;
  }
  return {
    createdAt: json['created_at'],
    createdBy: CreatedByFromJSON(json['created_by']),
    description: json['description'],
    fields: (json['fields'] as Array<any>).map(CustomSectionFieldFromJSON),
    id: json['id'],
    name: json['name'],
    status: CustomSectionStatusFromJSON(json['status']),
    updatedAt: json['updated_at'],
    updatedBy: UpdatedByFromJSON(json['updated_by']),
  };
}

export function CustomSectionToJSON(json: any): CustomSection {
  return CustomSectionToJSONTyped(json, false);
}

export function CustomSectionToJSONTyped(
  value?: CustomSection | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    created_at: value['createdAt'],
    created_by: CreatedByToJSON(value['createdBy']),
    description: value['description'],
    fields: (value['fields'] as Array<any>).map(CustomSectionFieldToJSON),
    id: value['id'],
    name: value['name'],
    status: CustomSectionStatusToJSON(value['status']),
    updated_at: value['updatedAt'],
    updated_by: UpdatedByToJSON(value['updatedBy']),
  };
}
