/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomSectionFieldType } from './CustomSectionFieldType';
import {
  CustomSectionFieldTypeFromJSON,
  CustomSectionFieldTypeFromJSONTyped,
  CustomSectionFieldTypeToJSON,
  CustomSectionFieldTypeToJSONTyped,
} from './CustomSectionFieldType';

/**
 *
 * @export
 * @interface CustomSectionField
 */
export interface CustomSectionField {
  /**
   *
   * @type {CustomSectionFieldType}
   * @memberof CustomSectionField
   */
  fieldType: CustomSectionFieldType;
  /**
   *
   * @type {string}
   * @memberof CustomSectionField
   */
  key: string;
  /**
   *
   * @type {string}
   * @memberof CustomSectionField
   */
  label: string;
}

/**
 * Check if a given object implements the CustomSectionField interface.
 */
export function instanceOfCustomSectionField(value: object): value is CustomSectionField {
  if (!('fieldType' in value) || value['fieldType'] === undefined) return false;
  if (!('key' in value) || value['key'] === undefined) return false;
  if (!('label' in value) || value['label'] === undefined) return false;
  return true;
}

export function CustomSectionFieldFromJSON(json: any): CustomSectionField {
  return CustomSectionFieldFromJSONTyped(json, false);
}

export function CustomSectionFieldFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CustomSectionField {
  if (json == null) {
    return json;
  }
  return {
    fieldType: CustomSectionFieldTypeFromJSON(json['field_type']),
    key: json['key'],
    label: json['label'],
  };
}

export function CustomSectionFieldToJSON(json: any): CustomSectionField {
  return CustomSectionFieldToJSONTyped(json, false);
}

export function CustomSectionFieldToJSONTyped(
  value?: CustomSectionField | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    field_type: CustomSectionFieldTypeToJSON(value['fieldType']),
    key: value['key'],
    label: value['label'],
  };
}
