/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CustomSectionFieldType = {
  Text: 'Text',
  Media: 'Media',
} as const;
export type CustomSectionFieldType =
  (typeof CustomSectionFieldType)[keyof typeof CustomSectionFieldType];

export function instanceOfCustomSectionFieldType(value: any): boolean {
  for (const key in CustomSectionFieldType) {
    if (Object.prototype.hasOwnProperty.call(CustomSectionFieldType, key)) {
      if (CustomSectionFieldType[key as keyof typeof CustomSectionFieldType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function CustomSectionFieldTypeFromJSON(json: any): CustomSectionFieldType {
  return CustomSectionFieldTypeFromJSONTyped(json, false);
}

export function CustomSectionFieldTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CustomSectionFieldType {
  return json as CustomSectionFieldType;
}

export function CustomSectionFieldTypeToJSON(value?: CustomSectionFieldType | null): any {
  return value as any;
}

export function CustomSectionFieldTypeToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): CustomSectionFieldType {
  return value as CustomSectionFieldType;
}
