/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FieldType } from './FieldType';
import {
  FieldTypeFromJSON,
  FieldTypeFromJSONTyped,
  FieldTypeToJSON,
  FieldTypeToJSONTyped,
} from './FieldType';

/**
 *
 * @export
 * @interface Field
 */
export interface Field {
  /**
   *
   * @type {FieldType}
   * @memberof Field
   */
  fieldType: FieldType;
  /**
   *
   * @type {any}
   * @memberof Field
   */
  value: any | null;
}

/**
 * Check if a given object implements the Field interface.
 */
export function instanceOfField(value: object): value is Field {
  if (!('fieldType' in value) || value['fieldType'] === undefined) return false;
  if (!('value' in value) || value['value'] === undefined) return false;
  return true;
}

export function FieldFromJSON(json: any): Field {
  return FieldFromJSONTyped(json, false);
}

export function FieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): Field {
  if (json == null) {
    return json;
  }
  return {
    fieldType: FieldTypeFromJSON(json['field_type']),
    value: json['value'],
  };
}

export function FieldToJSON(json: any): Field {
  return FieldToJSONTyped(json, false);
}

export function FieldToJSONTyped(value?: Field | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    field_type: FieldTypeToJSON(value['fieldType']),
    value: value['value'],
  };
}
