/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetContentQuery
 */
export interface GetContentQuery {
  /**
   *
   * @type {string}
   * @memberof GetContentQuery
   */
  categoryId?: string | null;
  /**
   *
   * @type {string}
   * @memberof GetContentQuery
   */
  keyword?: string | null;
  /**
   *
   * @type {number}
   * @memberof GetContentQuery
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof GetContentQuery
   */
  offset: number;
  /**
   *
   * @type {string}
   * @memberof GetContentQuery
   */
  relationSourceContentId?: string | null;
  /**
   *
   * @type {string}
   * @memberof GetContentQuery
   */
  statusKeys?: string | null;
  /**
   *
   * @type {string}
   * @memberof GetContentQuery
   */
  tags?: string | null;
}

/**
 * Check if a given object implements the GetContentQuery interface.
 */
export function instanceOfGetContentQuery(value: object): value is GetContentQuery {
  if (!('limit' in value) || value['limit'] === undefined) return false;
  if (!('offset' in value) || value['offset'] === undefined) return false;
  return true;
}

export function GetContentQueryFromJSON(json: any): GetContentQuery {
  return GetContentQueryFromJSONTyped(json, false);
}

export function GetContentQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetContentQuery {
  if (json == null) {
    return json;
  }
  return {
    categoryId: json['category_id'] == null ? undefined : json['category_id'],
    keyword: json['keyword'] == null ? undefined : json['keyword'],
    limit: json['limit'],
    offset: json['offset'],
    relationSourceContentId:
      json['relation_source_content_id'] == null ? undefined : json['relation_source_content_id'],
    statusKeys: json['status_keys'] == null ? undefined : json['status_keys'],
    tags: json['tags'] == null ? undefined : json['tags'],
  };
}

export function GetContentQueryToJSON(json: any): GetContentQuery {
  return GetContentQueryToJSONTyped(json, false);
}

export function GetContentQueryToJSONTyped(
  value?: GetContentQuery | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    category_id: value['categoryId'],
    keyword: value['keyword'],
    limit: value['limit'],
    offset: value['offset'],
    relation_source_content_id: value['relationSourceContentId'],
    status_keys: value['statusKeys'],
    tags: value['tags'],
  };
}
