/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetCategoryQuery
 */
export interface GetCategoryQuery {
  /**
   *
   * @type {number}
   * @memberof GetCategoryQuery
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof GetCategoryQuery
   */
  offset: number;
}

/**
 * Check if a given object implements the GetCategoryQuery interface.
 */
export function instanceOfGetCategoryQuery(value: object): value is GetCategoryQuery {
  if (!('limit' in value) || value['limit'] === undefined) return false;
  if (!('offset' in value) || value['offset'] === undefined) return false;
  return true;
}

export function GetCategoryQueryFromJSON(json: any): GetCategoryQuery {
  return GetCategoryQueryFromJSONTyped(json, false);
}

export function GetCategoryQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetCategoryQuery {
  if (json == null) {
    return json;
  }
  return {
    limit: json['limit'],
    offset: json['offset'],
  };
}

export function GetCategoryQueryToJSON(json: any): GetCategoryQuery {
  return GetCategoryQueryToJSONTyped(json, false);
}

export function GetCategoryQueryToJSONTyped(
  value?: GetCategoryQuery | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    limit: value['limit'],
    offset: value['offset'],
  };
}
