/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Media
 */
export interface Media {
  /**
   *
   * @type {string}
   * @memberof Media
   */
  key: string;
  /**
   *
   * @type {string}
   * @memberof Media
   */
  lastModified?: string | null;
  /**
   *
   * @type {string}
   * @memberof Media
   */
  size: string;
  /**
   *
   * @type {string}
   * @memberof Media
   */
  storageClass?: string | null;
  /**
   *
   * @type {string}
   * @memberof Media
   */
  url: string;
}

/**
 * Check if a given object implements the Media interface.
 */
export function instanceOfMedia(value: object): value is Media {
  if (!('key' in value) || value['key'] === undefined) return false;
  if (!('size' in value) || value['size'] === undefined) return false;
  if (!('url' in value) || value['url'] === undefined) return false;
  return true;
}

export function MediaFromJSON(json: any): Media {
  return MediaFromJSONTyped(json, false);
}

export function MediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Media {
  if (json == null) {
    return json;
  }
  return {
    key: json['key'],
    lastModified: json['last_modified'] == null ? undefined : json['last_modified'],
    size: json['size'],
    storageClass: json['storage_class'] == null ? undefined : json['storage_class'],
    url: json['url'],
  };
}

export function MediaToJSON(json: any): Media {
  return MediaToJSONTyped(json, false);
}

export function MediaToJSONTyped(value?: Media | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    key: value['key'],
    last_modified: value['lastModified'],
    size: value['size'],
    storage_class: value['storageClass'],
    url: value['url'],
  };
}
