/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Tag
 */
export interface Tag {
  /**
   *
   * @type {string}
   * @memberof Tag
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof Tag
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Tag
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Tag
   */
  updatedAt: string;
}

/**
 * Check if a given object implements the Tag interface.
 */
export function instanceOfTag(value: object): value is Tag {
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function TagFromJSON(json: any): Tag {
  return TagFromJSONTyped(json, false);
}

export function TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tag {
  if (json == null) {
    return json;
  }
  return {
    createdAt: json['created_at'],
    id: json['id'],
    name: json['name'],
    updatedAt: json['updated_at'],
  };
}

export function TagToJSON(json: any): Tag {
  return TagToJSONTyped(json, false);
}

export function TagToJSONTyped(value?: Tag | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    created_at: value['createdAt'],
    id: value['id'],
    name: value['name'],
    updated_at: value['updatedAt'],
  };
}
