/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateContentJson
 */
export interface UpdateContentJson {
  /**
   *
   * @type {Array<string>}
   * @memberof UpdateContentJson
   */
  categoryIds?: Array<string> | null;
  /**
   *
   * @type {string}
   * @memberof UpdateContentJson
   */
  customUrl?: string | null;
  /**
   *
   * @type {any}
   * @memberof UpdateContentJson
   */
  fields?: any | null;
  /**
   *
   * @type {Array<string>}
   * @memberof UpdateContentJson
   */
  relatedContentIds?: Array<string> | null;
  /**
   *
   * @type {any}
   * @memberof UpdateContentJson
   */
  seo?: any | null;
  /**
   *
   * @type {Array<string>}
   * @memberof UpdateContentJson
   */
  tagIds?: Array<string> | null;
  /**
   *
   * @type {any}
   * @memberof UpdateContentJson
   */
  thumbnail?: any | null;
  /**
   *
   * @type {string}
   * @memberof UpdateContentJson
   */
  title?: string | null;
}

/**
 * Check if a given object implements the UpdateContentJson interface.
 */
export function instanceOfUpdateContentJson(value: object): value is UpdateContentJson {
  return true;
}

export function UpdateContentJsonFromJSON(json: any): UpdateContentJson {
  return UpdateContentJsonFromJSONTyped(json, false);
}

export function UpdateContentJsonFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateContentJson {
  if (json == null) {
    return json;
  }
  return {
    categoryIds: json['category_ids'] == null ? undefined : json['category_ids'],
    customUrl: json['custom_url'] == null ? undefined : json['custom_url'],
    fields: json['fields'] == null ? undefined : json['fields'],
    relatedContentIds:
      json['related_content_ids'] == null ? undefined : json['related_content_ids'],
    seo: json['seo'] == null ? undefined : json['seo'],
    tagIds: json['tag_ids'] == null ? undefined : json['tag_ids'],
    thumbnail: json['thumbnail'] == null ? undefined : json['thumbnail'],
    title: json['title'] == null ? undefined : json['title'],
  };
}

export function UpdateContentJsonToJSON(json: any): UpdateContentJson {
  return UpdateContentJsonToJSONTyped(json, false);
}

export function UpdateContentJsonToJSONTyped(
  value?: UpdateContentJson | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    category_ids: value['categoryIds'],
    custom_url: value['customUrl'],
    fields: value['fields'],
    related_content_ids: value['relatedContentIds'],
    seo: value['seo'],
    tag_ids: value['tagIds'],
    thumbnail: value['thumbnail'],
    title: value['title'],
  };
}
