/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdatedBy
 */
export interface UpdatedBy {
  /**
   *
   * @type {string}
   * @memberof UpdatedBy
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof UpdatedBy
   */
  name: string;
}

/**
 * Check if a given object implements the UpdatedBy interface.
 */
export function instanceOfUpdatedBy(value: object): value is UpdatedBy {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function UpdatedByFromJSON(json: any): UpdatedBy {
  return UpdatedByFromJSONTyped(json, false);
}

export function UpdatedByFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatedBy {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
  };
}

export function UpdatedByToJSON(json: any): UpdatedBy {
  return UpdatedByToJSONTyped(json, false);
}

export function UpdatedByToJSONTyped(
  value?: UpdatedBy | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
  };
}
