/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateCategoryJson
 */
export interface UpdateCategoryJson {
  /**
   *
   * @type {string}
   * @memberof UpdateCategoryJson
   */
  apiIdentifier?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof UpdateCategoryJson
   */
  isPublished?: boolean | null;
  /**
   *
   * @type {string}
   * @memberof UpdateCategoryJson
   */
  name?: string | null;
}

/**
 * Check if a given object implements the UpdateCategoryJson interface.
 */
export function instanceOfUpdateCategoryJson(value: object): value is UpdateCategoryJson {
  return true;
}

export function UpdateCategoryJsonFromJSON(json: any): UpdateCategoryJson {
  return UpdateCategoryJsonFromJSONTyped(json, false);
}

export function UpdateCategoryJsonFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateCategoryJson {
  if (json == null) {
    return json;
  }
  return {
    apiIdentifier: json['api_identifier'] == null ? undefined : json['api_identifier'],
    isPublished: json['is_published'] == null ? undefined : json['is_published'],
    name: json['name'] == null ? undefined : json['name'],
  };
}

export function UpdateCategoryJsonToJSON(json: any): UpdateCategoryJson {
  return UpdateCategoryJsonToJSONTyped(json, false);
}

export function UpdateCategoryJsonToJSONTyped(
  value?: UpdateCategoryJson | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    api_identifier: value['apiIdentifier'],
    is_published: value['isPublished'],
    name: value['name'],
  };
}
