/* tslint:disable */
/* eslint-disable */
/**
 * BECRAFT API
 * BECRAFT API documentation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateTagJson
 */
export interface UpdateTagJson {
  /**
   *
   * @type {string}
   * @memberof UpdateTagJson
   */
  name?: string | null;
}

/**
 * Check if a given object implements the UpdateTagJson interface.
 */
export function instanceOfUpdateTagJson(value: object): value is UpdateTagJson {
  return true;
}

export function UpdateTagJsonFromJSON(json: any): UpdateTagJson {
  return UpdateTagJsonFromJSONTyped(json, false);
}

export function UpdateTagJsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTagJson {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
  };
}

export function UpdateTagJsonToJSON(json: any): UpdateTagJson {
  return UpdateTagJsonToJSONTyped(json, false);
}

export function UpdateTagJsonToJSONTyped(
  value?: UpdateTagJson | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
  };
}
